version: '3.8'
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: node_challenge
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  app:
    build: .
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - '3000:3000'
    command: ["node", "dist/index.js"]
    volumes:
      - .:/usr/src/app
    restart: always

volumes:
  db_data:
  redis_data:
